services:
  chadbox-api:
    build: .
    container_name: chadbox_core
    privileged: true
    volumes:
      - .:/app
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    working_dir: /app
    command: pnpm run dev
    ports:
      - '3000:3000'
