import { execSync, spawnSync } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import { type ExecutionConfig, type ExecutionResult } from './types.js';

export class Sandbox {
    private config: ExecutionConfig;
    private boxPath: string = '';

    constructor(config: ExecutionConfig) {
        this.config = config;
    }

    /**
     * Initialize the sandbox directory structure
     */
    public init(): string {
        try {
            // --cg enables control groups, crucial for memory limits
            const stdout = execSync(`isolate --init --cg --box-id=${this.config.boxId}`);
            this.boxPath = stdout.toString().trim();
            return this.boxPath;
        } catch (error: any) {
            throw new Error(`Failed to initialize sandbox ${this.config.boxId}: ${error.message}`);
        }
    }

    /**
     * Write the user's code into the isolated environment
     */
    public async writeCode(filename: string, code: string): Promise<void> {
        if (!this.boxPath) throw new Error("Sandbox not initialized");
        const fullPath = path.join(this.boxPath, 'box', filename);
        await fs.writeFile(fullPath, code);
    }

    /**
     * Execute the code and parse the metrics
     */
    public async run(executable: string, args: string[] = []): Promise<ExecutionResult> {
        if (!this.boxPath) throw new Error("Sandbox not initialized");

        const metaFile = path.join(this.boxPath, 'meta.txt');
        
        // Build the isolate command flags
        const isolateArgs = [
            '--run',
            '--cg',
            `--box-id=${this.config.boxId}`,
            `--time=${this.config.timeLimit}`,
            `--wall-time=${this.config.timeLimit + 1}`, // Add 1s buffer for wall time
            `--cg-mem=${this.config.memoryLimit}`,
            `--processes=${this.config.maxProcesses || 64}`,
            `--meta=${metaFile}`,
            '--',
            executable,
            ...args
        ];

        const result = spawnSync('isolate', isolateArgs, { encoding: 'utf-8' });

        return await this.parseMetaFile(metaFile, result.stdout, result.stderr, result.status);
    }

    /**
     * Destroy the sandbox and release cgroups
     */
    public cleanup(): void {
        try {
            execSync(`isolate --cleanup --cg --box-id=${this.config.boxId}`);
        } catch (error: any) {
            console.error(`Cleanup failed for box ${this.config.boxId}:`, error.message);
        }
    }

    /**
     * Reads the meta file generated by isolate to determine exact resource usage
     */
    private async parseMetaFile(metaPath: string, stdout: string, stderr: string, exitCode: number | null): Promise<ExecutionResult> {
        let memory = 0;
        let time = 0;
        let killedByOOM = false;
        let killedByTimeout = false;

        try {
            const metaContent = await fs.readFile(metaPath, 'utf-8');
            const lines = metaContent.split('\n');

            for (const line of lines) {
                if (line.startsWith('cg-mem:')) memory = parseInt(line.split(':')[1] || '0');
                if (line.startsWith('time:')) time = parseFloat(line.split(':')[1] || '0');
                if (line.includes('status: TO')) killedByTimeout = true;
                if (line.includes('status: SG') || line.includes('cg-oom-killed: 1')) killedByOOM = true;
            }
        } catch (e) {
            console.warn("Could not read meta file. Execution might have failed heavily.");
        }

        return {
            stdout: stdout || '',
            stderr: stderr || '',
            exitCode,
            time,
            memory,
            killedByOOM,
            killedByTimeout
        };
    }
}